spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/coupons_project
    username: root
    password: DA9456131
    driverClassName: com.mysql.cj.jdbc.Driver

